language: node_js
node_js: 8
script:
  - npm run lint
  - npm run build
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  yarn: true
env:
  global:
    # CHROME_CLIENT_ID
    - secure: WF3EoZHRGwrl155p7q4SW2HRHRyY6xy8oK7NfLyjjtrCTyrBt5y5eQAwBC7lj1tIoFhGTti1CV9oLpPFvzWbM+TQslTTSpdGaGYD//aWcCw/1IJqP6AALbeTZ5zH6QybRF+lXFHDfEiEIIAacXWpa0uz4Jkd9DnTNL9lBjwS7xsQBzMc/OpnzicWPcwBwZjmBVQwoUMLsZSeZeFtINX2N3BDtPJa6ffKvvNimXDTvExcqydztg+zds+FOW/z5bluEauUvdVI82ArpzVtbIFhmayRoZetay2WjYxQdtZx9kiSyodKKGLvU3SKXMFhFvJr1z7Kt1/7HJAiE2aeuBoep4Uw55t3hJda8054v0SgdUJRS7/aKduIWsKIjXSsi5WpsNGcRkQA2WFmEaaVvaURqamKcj6bx/SH8mXdeWPm6GPcnc+yOjwe5y2pdtfOkt3CzNUHsLANZ8r5ATiu5Bksc58J4yW9gLWpdyb2Tj5FXg9VFfMjhpNkb0PqCBvdnk4nB9Ej/wpkA9SB00DtCqpbwPNUdMUjI/iRKsDb4k6kOeLM05Dr+SvAtB9xJqnqaM7Lg5WKLa26GdSMWzgzlr1RD8J6i64WpPG9x/K+ry0ug/7PBjdjiXFVtHgyHZEfnG7jAqViNthTjTBRK5sP0cxTYDYaDG6bLhPyzhfrkx5kX+o=
    # CHROME_CLIENT_SECRET
    - secure: KH9+yz7ETbblQS6XR0YstTTXpMGdahz42G8vMK2s5Zak538bVqao5x026fJxO1ylNs6D2KTIEFHWW8KeheiJS8NYcEFA8E5XT5c6bgoGlg68zUgHbFbU/54Sx33p1S1m8UL+6A2N5xdcwdytqfknLTwztoONOmmQW0sz2f3K9AV1Bilq17Np09aGuDmdmk4McEgadv1iGeMr3E8EhJkITo0kQ4Q13RqtMyz6KWjwX0zfInslM7byfmH5L8VB6cIX3x+zxHJYntbnSAOzvbXuNuVdkrlJKpvs3XKTegYe1YOJluuAhF+HyqgQEt3dNRUXzBzhghNkIpWc2QnymHg14j5A4P4bpj43VKhhfTMYalFGII7Iak49dqz7pBL3ZbfHq5ZLCKblz1CtCan5nozspSadWEHOAdT3150+T0NGEek/RPJVpu8yUvNzzAcGQqJEqOFB4J2gjdwwgVd/8HpI4KHjmUouA7MSclccFx/URUmeGK/780mT4TyraNWo8kFwdM5WIQirchcRITXvQyfds58m1hZYiSy89pV4bY3muvpVSkuOxFQGnSDTkkvdxOwp2BdIH3ximwV2XFGFFnxneGqnZErRWvUwoMPC0xEMZwZ5sqnPF0Ynyf3kd8gaVGdS6e/qvVyyxZK5Tj6NwMiaKGhLPhCouRf9bGRLcXYTEHQ=
    # CHROME_REFRESH_TOKEN
    - secure: W7DdQdoEXIyPOwITUxcLq0Tnpi6X4MlyGYr8iIWSzSqv6RPb8qy5nhxmEPSBpqxObffhOIwa5gXcZXxFHFvRAJZyEk/v36DiMI980ppq1aKuU6aGe/kPzSUrBPL9k58idW4UXG9RJM4IGX7gl0IGE9S68lnvkLJlCuZ/jQSKg6pwglFeZQPTWOkH7luFPYk3Vxsj8gUNdp/IE7b5kIucGSOoEUDTCUjOUrgFQw8QlO9BKlHOhdPWFa4lc0AvXtHkNbPDYq7+P744l/ttiLzGbIoFXs1H2ktvZIYo6gginXAmBpaejv4ipDZiEe3a1oFSx0F3bbiE8PCOt88Fhftn5zCenDbOKj2eUp8NBsHlR630MRZQNl24FGdDFD3Tu31Ue6uhke8wnv4xlPZhwoPXeDP01pgKjbiQoqPRpS/ud9s01o3DmtQ3oPRTK6pmIER55YM6SoYeobaSL2MWvoh5VZ5FZBv1q4hXSAil1chiavFaji/v7mMUtEcb5Sm8twZVGl1PZynb5+0dPS/05HEiMKO3fhsEU06X/umbqzQbhQlbnC3o0zn9wbJW1KeTddNWyYcLci7WUxQAET99otYQuagKblQZwPv9m6hFCFtaSx7fhCMvAYJakRK9W8TRZBYjD0v7B78csBABygSKMmx6Ow54Sm1gYTWZn65UB7/nmew=
deploy:
  - provider: releases
    api_key:
      secure: QLJm3hqvr4b3Pkrb1vmwkHC6fmML9L6qLMxO7HNhqfD7yombObcESqd/JJrM7xdXCCeihBbOFcro/xHe1mOuNC57BCUISvIRRIKhn8otlOq+iZLyyR8y6sn2G/LZ9/LdeZIKxi6E6S/gDscV0tKqLBCJp+2hsoeL+5miwKO5ADa3ovuIc//TOrQles+j1Np15Srd4UuRtaEjF19yPSPBZdKWlBG6qrtyqehdE1R2WEMqhBQL0aWmjyDxFaXVkUOLLHwbVitU9mHoe7tmZMOSxZrqzNnEU+svfmW9O4X/8z1XsohIk3RAdpjQp626T9vwtcWX0UySV+llf9OnD83g1cBcQbXBX/6s4pTSt9lA7hU5mOYj1xiEE/7IlnfZ47iGxPSqXARLUDejmurWhu1tJv+9SLR/qSXtjLubQpi7fWbGhbbkvkvC0ABi4uqy81GSoRxiANjWUA1nJ3tqG0dontkcDglJtVrAMMz/g8r4m+Y44WNc4q+8Rrxi/IZ3dAuHGpLtwLg/RUV1mSo90DInQkeokg2NJQb81ChQKeibfeZkEGZgZ6nJ7sS7BFjXwyZAxTLGNetWGvZGIooAiyphlBca7NuTozIA03/M2BLZ6A3MLmTVFPdItMwrZLwhcSsrOge5DAVTlHR929pOIYTnjvj3M/Jsj9YpUudutHb4miI=
    file: dist/GMK.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
      tags: true
